name: firebase_user_repository
description: "firebase_user_repository for flutter_user package"
version: 6.0.0
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  user_repository_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_user
      ref: 6.0.0
      path: packages/user_repository_interface
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
