name: flutter_user
description: "Flutter Userstory for onboarding, login, and registration."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: any
  flutter_login:
    git:
      url: https://github.com/Iconica-Development/flutter_login_widget
      ref: 5.2.0
  flutter_login_service:
    git:
      url: https://github.com/Iconica-Development/flutter_login_service
      path: packages/flutter_login_service
      ref: 2.0.0
  flutter_registration:
    git:
      url: https://github.com/Iconica-Development/flutter_registration
      ref: 1.0.0
  flutter_form_wizard:
    git:
      url: https://github.com/Iconica-Development/flutter_form_wizard
      ref: 6.2.5
  flutter_stepper:
    git:
      url: https://github.com/Iconica-Development/stepper
      ref: 2.2.0
  flutter_profile:
    git:
      url: https://github.com/Iconica-Development/flutter_profile
      ref: 1.3.0
  flutter_image_picker:
    git:
      url: https://github.com/Iconica-Development/flutter_image_picker
      ref: 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
  uses-material-design: true
