name: flutter_user
description: "Flutter Userstory for onboarding, login, and registration."
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub
version: 5.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_login:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.1.3
  flutter_input_library:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^3.6.0
  flutter_login_service:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^5.0.0
  flutter_registration:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^3.0.1
  flutter_image_picker:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^4.0.0
  flutter_profile:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^1.6.0

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
flutter:
  uses-material-design: true
