name: flutter_user
description: "Flutter Userstory for onboarding, login, and registration."
publish_to: none
version: 6.0.1

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_input_library:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: 3.7.0
  flutter_image_picker:
    git:
      url: https://github.com/Iconica-Development/flutter_image_picker
      ref: 4.1.0
  user_repository_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_user
      ref: 6.0.1
      path: packages/user_repository_interface
  flutter_profile:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^1.6.0

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
